# Generated by Django 3.2.8 on 2022-02-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0002_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
